### ISSUE TITLE
IndexOutOfBounds when joining an arena without specifying a number

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#28]
When a player types `/scb join` without specifying an arena number, an IndexOutOfBounds exception is generated.

```
[23:55:53 INFO]: Marshox66 issued server command: /scb join
[23:55:53 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[23:55:53 WARN]:        at org.mcsg.double0negative.supercraftbros.commands.JoinCommand.onCommand(JoinCommand.java:14)
[23:55:53 WARN]:        at org.mcsg.double0negative.supercraftbros.CommandHandler.onCommand(CommandHandler.java:95)
[23:55:53 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:55:53 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:55:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1166)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:55:53 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:55:53 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:766)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:705)
[23:55:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:608)
[23:55:53 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by justwheel** [comment]
@nextinfinity This still happens in 1.3.3.

```
[15:02:28 INFO]: jflory7 issued server command: /scb join
[15:02:28 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[15:02:28 WARN]:        at org.mcsg.double0negative.supercraftbros.commands.JoinCommand.onCommand(JoinCommand.java:14)
[15:02:28 WARN]:        at org.mcsg.double0negative.supercraftbros.CommandHandler.onCommand(CommandHandler.java:95)
[15:02:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:02:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:02:28 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1165)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1000)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:02:28 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:02:28 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
[15:02:28 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
[15:02:28 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
