### ISSUE TITLE
Game does not end when fails to start for not enough players

### ISSUE THREAD

**Issue by justwheel** [nextinfinity/SuperCraftBros#31]
I was in a game lobby and the timer had started, yet once it had gone down to zero, the game didn't start. I don't know if @Saphiria had left the lobby or if it was just two of us in the game, but this message fired.
![Failed to start](http://i.j-f.co/u/e8c68a045c986b5456167a27a9018489.png)

After this, I did `/scb leave` inside of our lobby, but strange behavior was still going on. Whenever I tried going to spawn or joining another arena, my character would not teleport and I couldn't leave my location. Upon trying to `/kill` my character, my scoreboard popped back up and showed me inside of a game. Additionally, this stacktrace fired in console as well.

```
[22:54:58 INFO]: jflory7 issued server command: /kill jflory7
[22:54:58 ERROR]: Could not pass event PlayerDeathEvent to SuperCraftBros-SmashEdition v1.2.3-R1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:395) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:87) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:40) [EssentialsX.jar:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:98) [EssentialsX.jar:?]
        at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:23) [EssentialsX.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:151) [EssentialsX.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:428) [EssentialsX.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:338) [EssentialsX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1166) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:766) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:705) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:608) [paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
        at org.mcsg.double0negative.supercraftbros.event.PlayerClassEvents.onEntityDeath(PlayerClassEvents.java:138) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor198.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paperspigot.jar:git-PaperSpigot-56afbe3-d27e6d0]
        ... 29 more
```

**Comment by justwheel** [comment]
(Also, for the record, the "SmashEdition" is just my fork with the modified, hard-coded classes. It's completely based off of 16c3f5e2aec7905813ebe4b0d7713eef07e60dbe.)
